name: run-tests

on:
  push:
  pull_request:
  workflow_dispatch:
  # schedule:
  #   - cron: "5 1 * * *"

jobs:
  unittesting:
    name: unit testing (Go ${{ matrix.go }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ ">=1.19.1" ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{ matrix.go }}

      # Caching go modules to speed up the run
      - uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run Unit tests.
        run: make test